### ISSUE TITLE
Arrival time not passed to the URL

### ISSUE THREAD

**Issue by mhpob** [jlacko/gmapsdistance#5]
Regardless of anything I pass to the  `arrival`, `arr_date`, or `arr_time` argument, I get the same, present, trip time back. It looks like `seconds_arrival` variable made from these arguments never actually gets put into the API call.

https://github.com/jlacko/gmapsdistance/blob/master/R/gmapsdistance.R#LL283C15-L283C15

https://github.com/jlacko/gmapsdistance/blob/master/R/gmapsdistance.R#L349-L355

**Comment by jlacko** [comment]
Thanks for the pointer, at the first glance it truly looks as if the parameter gets lost in translation.

I will double check and implement a fix if confirmed (which seems likely)

**Comment by jlacko** [comment]
I have:
1) created a new unit test that the current CRAN version was failing (comparing arrival times on public transport at midday and midnight / there was no difference)
2) implemented a fix so that the unit test is passing (travel time on public transport at midnight is significantly slower than at midnight)

The github version of package should should be OK shortly, with CRAN taking a while longer due to the governance involved.

If you don't mind trying out the github version 4.0.2 I would appreciate a double check.
